const ProfileTypes = {
  GET_PROFILE: " GET_PROFILE",
  PROFILE_LOADING: "PROFILE_LOADING",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  GET_ACCOUNT: "GET_ACCOUNT"
};
export default ProfileTypes;
